/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Image1Image from 'src/assets/images/Desktop1Default_image_1.png';
import VectorImage from 'src/assets/images/Desktop1Default_Vector.png';
import Vector1Image from 'src/assets/images/Desktop1Default_Vector_1.png';
import Vector3Image from 'src/assets/images/Desktop1Default_Vector_3.png';
import Vector2Image from 'src/assets/images/Desktop1Default_Vector_2.png';
import Vector4Image from 'src/assets/images/Desktop1Default_Vector_4.png';
import Image3Image from 'src/assets/images/Desktop1Default_image_3.png';
import Image31Image from 'src/assets/images/Desktop1Default_image_3_1.png';
import Image32Image from 'src/assets/images/Desktop1Default_image_3_2.png';
import Image33Image from 'src/assets/images/Desktop1Default_image_3_3.png';
import Vector5Image from 'src/assets/images/Desktop1Default_Vector_5.png';
import { styled } from '@mui/material/styles';

const Desktop1Default1 = styled('div')({
  backgroundColor: `rgba(38, 38, 38, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1990px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Group1 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1160px`,
  height: `748px`,
  left: `140px`,
  top: `347px`,
});

const Image2 = styled('div')({
  background: `linear-gradient(90deg, rgba(0, 0, 0, 1) -0.00000837718830517837%, rgba(0, 0, 0, 0.13) 47.068959945582215%)`,
  borderRadius: `17px`,
  width: `1160px`,
  height: `748px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Image1 = styled('img')({
  height: `389px`,
  width: `278px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `60px`,
  top: `267px`,
});

const Frame1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `12.194092750549316px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `7.172995567321777px 33.71308135986328px`,
  boxSizing: `border-box`,
  left: `275px`,
  top: `549px`,
});

const Q100 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(50, 50, 50, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `600`,
  fontSize: `37.29957962036133px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Q83 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `26.47272491455078px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `398px`,
  top: `503px`,
});

const Q = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(139, 139, 139, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `underline`,
  textTransform: `none`,
  position: `absolute`,
  left: `360px`,
  top: `626px`,
});

const Vector = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `360px`,
  top: `506px`,
});

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `600`,
  fontSize: `37.29957962036133px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `134px`,
  top: `1183px`,
});

const Q2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `600`,
  fontSize: `37.29957962036133px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `134px`,
  top: `254px`,
});

const Vector1 = styled('img')({
  height: `0px`,
  width: `24px`,
  position: `absolute`,
  left: `508px`,
  top: `1209px`,
});

const Vector3 = styled('img')({
  height: `0px`,
  width: `24px`,
  position: `absolute`,
  left: `483px`,
  top: `280px`,
});

const Vector2 = styled('img')({
  height: `0px`,
  width: `709px`,
  position: `absolute`,
  left: `590px`,
  top: `1209px`,
});

const Vector4 = styled('img')({
  height: `0px`,
  width: `737px`,
  position: `absolute`,
  left: `562px`,
  top: `280px`,
});

const Group6 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1159px`,
  height: `445px`,
  left: `140px`,
  top: `1276px`,
});

const Group2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `260px`,
  height: `445px`,
  left: `0px`,
  top: `0px`,
});

const Q3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `416px`,
});

const Q2015 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(208, 208, 208, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `382px`,
});

const Image3 = styled('img')({
  height: `363px`,
  width: `260px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame2 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `9px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `7.5px`,
  boxSizing: `border-box`,
  width: `37px`,
  height: `22px`,
  left: `17px`,
  top: `13px`,
});

const Q831 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(50, 50, 50, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Group3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `260px`,
  height: `445px`,
  left: `300px`,
  top: `0px`,
});

const Q4 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `416px`,
});

const Q2017 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(208, 208, 208, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `382px`,
});

const Image31 = styled('img')({
  height: `363px`,
  width: `260px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame21 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `9px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `7.5px`,
  boxSizing: `border-box`,
  width: `37px`,
  height: `22px`,
  left: `17px`,
  top: `13px`,
});

const Q72 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(50, 50, 50, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Group4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `260px`,
  height: `445px`,
  left: `600px`,
  top: `0px`,
});

const R2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `260px`,
  position: `absolute`,
  left: `0px`,
  top: `416px`,
});

const Q2008 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(208, 208, 208, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `382px`,
});

const Image32 = styled('img')({
  height: `363px`,
  width: `260px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame22 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `9px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `7.5px`,
  boxSizing: `border-box`,
  width: `37px`,
  height: `22px`,
  left: `17px`,
  top: `13px`,
});

const Q87 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(50, 50, 50, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Group5 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `260px`,
  height: `445px`,
  left: `899px`,
  top: `0px`,
});

const Q5 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `416px`,
});

const Q2006 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(208, 208, 208, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `382px`,
});

const Image33 = styled('img')({
  height: `363px`,
  width: `260px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame23 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `9px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `7.5px`,
  boxSizing: `border-box`,
  width: `37px`,
  height: `22px`,
  left: `17px`,
  top: `13px`,
});

const Q86 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(50, 50, 50, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Rectangle1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `17px`,
  width: `960px`,
  height: `73px`,
  position: `absolute`,
  left: `140px`,
  top: `118px`,
});

const Rectangle2 = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `17px`,
  width: `180px`,
  height: `73px`,
  position: `absolute`,
  left: `1120px`,
  top: `118px`,
});

const Q1001 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1002px`,
  top: `40px`,
});

const Q6 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1245px`,
  top: `40px`,
});

const Q7 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `140px`,
  top: `40px`,
});

const Q8 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `305px`,
  top: `40px`,
});

const Q9 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `463px`,
  top: `40px`,
});

const Q10 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `632px`,
  top: `40px`,
});

const Q11 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `300`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `875px`,
  top: `40px`,
});

const Q12 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1183px`,
  top: `142px`,
});

const Q13 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(199, 199, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `TT Hoves`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `258px`,
  top: `142px`,
});

const Vector5 = styled('img')({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `180px`,
  top: `139px`,
});

function Desktop1Default(props) {
  return (
    <Desktop1Default1 className={props.className}>
      <Group1>
        <Image2></Image2>
        <Image1 src={Image1Image} loading="lazy" alt={'image 1'} />
        <Frame1>
          <Q100>{`Моб Психо 100`}</Q100>
        </Frame1>
        <Q83>{`8.3`}</Q83>
        <Q>{`обсудить`}</Q>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      </Group1>
      <Q1>{`Посмотрите так же`}</Q1>
      <Q2>{`Случайное аниме`}</Q2>
      <Vector1 src={Vector1Image} loading="lazy" alt={'Vector 1'} />
      <Vector3 src={Vector3Image} loading="lazy" alt={'Vector 3'} />
      <Vector2 src={Vector2Image} loading="lazy" alt={'Vector 2'} />
      <Vector4 src={Vector4Image} loading="lazy" alt={'Vector 4'} />
      <Group6>
        <Group2>
          <Q3>{`Ванпанчмен`}</Q3>
          <Q2015>{`2015`}</Q2015>
          <Image3 src={Image3Image} loading="lazy" alt={'image 3'} />
          <Frame2>
            <Q831>{`8.3`}</Q831>
          </Frame2>
        </Group2>
        <Group3>
          <Q4>{`Инуясики`}</Q4>
          <Q2017>{`2017`}</Q2017>
          <Image31 src={Image31Image} loading="lazy" alt={'image 3'} />
          <Frame21>
            <Q72>{`7.2`}</Q72>
          </Frame21>
        </Group3>
        <Group4>
          <R2>{`Код Гиас: Восставший Лелуш R2`}</R2>
          <Q2008>{`2008`}</Q2008>
          <Image32 src={Image32Image} loading="lazy" alt={'image 3'} />
          <Frame22>
            <Q87>{`8.7`}</Q87>
          </Frame22>
        </Group4>
        <Group5>
          <Q5>{`Тетрадь смерти`}</Q5>
          <Q2006>{`2006`}</Q2006>
          <Image33 src={Image33Image} loading="lazy" alt={'image 3'} />
          <Frame23>
            <Q86>{`8.6`}</Q86>
          </Frame23>
        </Group5>
      </Group6>
      <Rectangle1></Rectangle1>
      <Rectangle2></Rectangle2>
      <Q1001>{`Топ-100`}</Q1001>
      <Q6>{`войти`}</Q6>
      <Q7>{`Сериалы`}</Q7>
      <Q8>{`Фильмы`}</Q8>
      <Q9>{`Онгоинги`}</Q9>
      <Q10>{`Случайное аниме`}</Q10>
      <Q11>{`Блог`}</Q11>
      <Q12>{`найти`}</Q12>
      <Q13>{`Дропкик злого духа...`}</Q13>
      <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
    </Desktop1Default1>
  );
}

export default Desktop1Default;
